### ISSUE TITLE
Log not work

### ISSUE THREAD

**Issue by Cripix** [polvora/SteamCore#12] opened 2017-08-21 19:37 UTC
Hello !

I installed the new version of the plugin.

But debug mode does not work ,logs are not written.

Can you fix it?

Thanks

**Comment by polvora** [comment] 2017-08-21 19:49
This is weird because this is working for me, do you check if the plugin even loaded?
type `rcon sm plugins list`

**Comment by Cripix** [comment] 2017-08-21 19:55
01 "Admin File Reader" (1.8.0.6024) by AlliedModders LLC
  02 "CS:GO Goremod" (1.3) by Joe 'DiscoBBQ' Maley
  03 "SourceBans++: Main Plugin" (1.6.2) by SourceBans Development Team, SourceBans++ Dev Team
  04 "[CS:GO] Show legit profile rank on scoreboard" (1.3) by Laam4
  05 "VPP Advertisement Plugin" (1.4.1) by VPP Network & SM9(xCoderx)
  06 "SimpleCSGOAntiAFK" (0.0.8) by Puppetmaster
  07 "SourceBans++: Bans Checker" (1.6.2) by psychonic, Ca$h Munny, SourceBans++ Dev Team
  08 "CS:GO GiveNamedItem Hook Franug Edition" (4.0.5 private version) by Franc1sco franug and Neuro Toxin
  09 "SM Valve Gloves" (1.3.7) by Franc1sco franug and hadesownage
  10 "Fun Votes" (1.8.0.6024) by AlliedModders LLC
  11 "SourceBans++: SourceSleuth" (1.6.2) by ecca, SourceBans++ Dev Team
  12 "Dynamic" (0.0.29) by Neuro Toxin
  13 "Player Commands" (1.8.0.6024) by AlliedModders LLC
  14 "Fast Team Balancer" (1.0.6) by [W]atch [D]ogs
  15 "WebLync" (0.0.11) by Neuro Toxin
  16 "Group players" (1.1) by boomix
  17 "Reserved Slots" (1.8.0.6024) by AlliedModders LLC
  18 "Sound Commands" (1.8.0.6024) by AlliedModders LLC
  19 "Fun Commands" (1.8.0.6024) by AlliedModders LLC
  20 "SourceBans++: SourceComms" (1.6.2) by Alex, SourceBans++ Dev Team
  21 "Rules Plugin" (1.1) by haN
  22 "Basic Chat" (1.8.0.6024) by AlliedModders LLC
  23 "[CSGO] Advanced Admin" (1.6.1) by PeEzZ
  24 "Nextmap" (1.8.0.6024) by AlliedModders LLC
  25 "Basic Info Triggers" (1.8.0.6024) by AlliedModders LLC
  26 "csgotokens.com token changer" (1.2.1) by Adi - live4net
  27 "ServerAdvertisements3" (3.1.3) by ESK0
  28 "Admin Menu" (1.8.0.6024) by AlliedModders LLC
  29 "Anti-Flood" (1.8.0.6024) by AlliedModders LLC
  30 "Basic Comm Control" (1.8.0.6024) by AlliedModders LLC
  31 "CS:GO Admin ESP" (2.1) by Root
  32 "WS - csgotokens.com" (1.06) by Adi - live4net
  33 "Steam Works Group Manager" (1.7) by Someone
  34 "tVIP" (2.1) by Totenfluch
  35 "DR.API SHOW DAMAGE" (1.1.2) by Dr. Api
  36 "[LR] Core" (v2.3.1) by RoadSide Romeo
  37 "Report tool" (1.0) by Reo
  38 "Basic Commands" (1.8.0.6024) by AlliedModders LLC
  39 "Knife Upgrade" (2.5.7) by Klexen
  40 "Basic Votes" (1.8.0.6024) by AlliedModders LLC
  41 "SourceBans++: Admin Config Loader" (1.6.2) by AlliedModders LLC, SourceBans++ Dev Team
  42 "[Scoreboard] Tags-Fix" (0.2) by .P4NDAzz
  43 "Client Preferences" (1.8.0.6024) by AlliedModders LLC
  44 "Admin Help" (1.8.0.6024) by AlliedModders LLC
  45 "[SWGM] Command Listener" (1.1) by Someone
  46 "SteamCore" (2.0) by Statik
  47 "Steam Inviter" (1.6) by Simon

**Comment by Cripix** [comment] 2017-08-21 20:08
OK now I know why logs works

But I have another problem with logs gives me an error code=
Login request returned with error code: 11 (0 = success)

**Comment by yash1441** [comment] 2017-08-21 20:20
Steam authenticator is disabled, need to enable it.

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by polvora** [comment] 2017-08-21 20:25
https://store.steampowered.com/twofactor/manage
Go to that site with that account you are using for the plugin and select _Get Steam Guard codes by email_

**Comment by polvora** [comment] 2017-08-21 20:27
Please read the README file and follow the instructions to configure your account.

**Comment by yash1441** [comment] 2017-08-22 16:00
Can confirm it works. Had a friend also check it in his server with a different account and it worked.

**Comment by Cripix** [comment] 2017-08-23 17:51
Hello !
Sorry to have put a little time to answer but it works !!!!

But the plugin can only send an invitation to the person it is normal?

Thanks

**Comment by polvora** [comment] 2017-08-23 17:54
Glad to hear it works!

What do you mean with can only send an invitation? Isn't that what you wanted?

**Comment by Cripix** [comment] 2017-08-23 18:10
Yes but I would like it to be every time the person log on to the server.

Because currently it's just once and he says "This user has already been invited or is currently a member

**Comment by yash1441** [comment] 2017-08-23 18:29
The account that you use for inviting is an account like everybody else's. Just like you can't invite people to your group if they still have an invite from you pending from earlier.

**Comment by polvora** [comment] 2017-08-23 20:13
As the issue is solved im closing it.

**Closed by polvora** 2017-08-23 20:13 UTC
Labels: help wanted
